// <auto-generated />
using Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Data.Migrations
{
    [DbContext(typeof(WoningContext))]
    [Migration("20211001121118_WoningDB")]
    partial class WoningDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company.Data.Bewoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WoningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WoningId");

                    b.ToTable("Bewoner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Joosten",
                            WoningId = 2
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Verschoor",
                            WoningId = 2
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Rubens",
                            WoningId = 3
                        },
                        new
                        {
                            Id = 4,
                            Naam = "Van Zanten",
                            WoningId = 3
                        });
                });

            modelBuilder.Entity("Company.Data.Woning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Woning");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Huisnummer = 0,
                            Naam = "zelftevree"
                        },
                        new
                        {
                            ID = 3,
                            Huisnummer = 0,
                            Naam = "boslust"
                        });
                });

            modelBuilder.Entity("Company.Data.Bewoner", b =>
                {
                    b.HasOne("Company.Data.Woning", "Woning")
                        .WithMany("Bewoners")
                        .HasForeignKey("WoningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Woning");
                });

            modelBuilder.Entity("Company.Data.Woning", b =>
                {
                    b.Navigation("Bewoners");
                });
#pragma warning restore 612, 618
        }
    }
}
